### ISSUE TITLE
1장 - 질문정리

### ISSUE THREAD

**Issue by HyoungUkJJang** [whyWhale/object-study#1]
### 1장을 읽으면서 궁금했던 점을 자유롭게 남겨주세요 :)

**Comment by whyWhale** [comment]
- 무읖을 두둥~탁! 치고 갑니다 (매우 잘 이해했다는 의미)

**Comment by ynoolee** [comment]
이번 챕터는 익숙한 개념들로만 쭉 진행되어 편하게 읽었슴다🐳

**Comment by HyoungUkJJang** [comment]
객체지향의 사실과 오해에 나왔던 내용들이 많이 나와있어서 좋은 책인 것 같아요 :) 

1장은 그만큼 익숙한 내용들이 나와서 크게 어려움 없이 읽을 수 있었습니다 ! 
특별히 궁금한 내용은 없었습니다 ~!

**Comment by YHLEE9753** [comment]
절차지향은 프로세스와 데이터를 별도의 모듈에 위치시키는 것이고 객체지향은 데이터와 프로세스가 동일한 모듈 내부에 위치한다고 하는데 처음 이문장을 보았을때는 이해가 안되었는데 뒷 글을 보니 이해가 되었네요. 객체지향과 절차지향에 대해서 자신만의 언어로 정리해보아도 좋을거 같습니다! 객체의 자율성, 책임, 협력을 코드를 개선하면서 객체지향의 사실과 오해를 실습해보는 시간인거 같아 좋았습니다.

**Comment by pjh612** [comment]
객체 지향과 절차지향을 설명하고, 결합도와 응집도를 설명하는 시간을 가지면 좋을 것 같습니다~
