### ISSUE TITLE
2장 (56p ~ 72p) - 질문정리

### ISSUE THREAD

**Issue by whyWhale** [whyWhale/object-study#11]
56p ~ 72p 까지 궁금했던 점, 느낀 점 등 자유롭게 남겨주세 🐉

**Comment by whyWhale** [comment]
아직까지는 따로 질문 없이 무난하게 읽을 수 있던 chpater 였던것 같습니다.

코드도 코드지만 좋은 설계를 고민하는 것은 정말 어렵다고 느끼네요 .. 
<img width="367" alt="??" src="https://user-images.githubusercontent.com/67587446/188518315-31efd981-db20-45e7-a7b3-8e364132f01e.png">

**Comment by ynoolee** [comment]
내용자체는 무난했지만 저의 경우 말로 설명하라고 하면 어렵게 느껴지는 것 같습니다. 
그래서 
1. 추상 클래스와 인터페이스
2. 합성과 상속
에 대해서 얘기해보면 좋을 것 같습니다

**Comment by pjh612** [comment]
저번에 얘기 나눴던 추상클래스를 사용할지 인터페이스를 사용할지 이번 분량을 읽고 생각이 바뀌었는지? 아니면 그대로인지 나눠보면 좋을 것 같아요

추상화 정의를 저번에 제대로 하지 못했었는데 책에서 언급을 해줘서 책에 나와있는 내용 토대로 다시 한번 얘기해봐도 좋을 것 같습니다.
여러분들이라면 NoneDiscountPolicy를 위해  DiscountPolicy를 인터페이스로 만들것 같나요?

**Comment by HyoungUkJJang** [comment]
저도 연우님과 느낀점이 비슷합니다. 
내용 자체를 읽기에는 무리가 없이 이해가 되지만 이것을 직접 말로 설명해보라고 하면 너무 어려울 것 같네요..!

진형님과 연우님께서 말씀해주신 부분에 대해 이야기해보는 것에 대해 저도 찬성합니다 :)

**Comment by YHLEE9753** [comment]
- 의존성의 양면성이 설계의 트레이드오프라는 말이 인상깊었습니다
- 상속의 장단점과 이를 보안하는 합성이 무엇인지 합성은 단점이 없는지에 대해 의논하면 좋을거 같습니다.
- 68쪽 내용에 대해서 이야기 나누고 싶습니다~
