### ISSUE TITLE
3장 - 질문정리 [협력, 책임 까지]

### ISSUE THREAD

**Issue by YHLEE9753** [whyWhale/object-study#15]
3장을 읽으면서 궁금했던 점을 자유롭게 남겨주세요 :)

**Comment by YHLEE9753** [comment]
객체지향의 사실과 오해를 3장이라는 챕터로 요약한 것 같습니다. 목적 - 협력 - 책임,역할 - 행동 - 상태 에서 추상화를 통해 행동들을 역할로 묶을 수 있다로 정리할 수 있을거같습니다.

**Comment by ynoolee** [comment]
협력의 문맥에 따라 필요한 행동들이 달라지기 때문에, 협력의 문맥을 먼저 정의하는 것이 중요하다 생각되었습니다. 
협력  - > 책임, 행동 -> 객체에게 할당 -> 객체의 상태
의 흐름으로 이어나가는 것으로 생각하면 좋을 것 같습니다. 

이번 범위는 어려운 내용은 없었던 것 같습니다!
