### ISSUE TITLE
2장(~55p) - 질문정리 

### ISSUE THREAD

**Issue by HyoungUkJJang** [whyWhale/object-study#8]
2장 55p까지 읽고 궁금했던 점 or 느낀 점 or 이야기해보면 좋을 것 같은 의견을 자유롭게 남겨주세요 ~

**Comment by HyoungUkJJang** [comment]
개인적으로 저는 전에 스터디에서 얘기했던 캡슐화에 대해 이야기가 나와서 좋았습니다 !

이번 내용에도 크게 어려웠던 부분은 없었기 때문에 도메인, 추상화, 다형성 등의 개념을 한번 더 정리해보면 좋을 것 같아요 ~

**Comment by pjh612** [comment]
DiscountPolicy를 인터페이스로 만드는 것은 어떨지 얘기 해보면 좋을 것 같습니다.

왜 저자가 추상 클래스를 사용했고 어떨때 추상 클래스를 사용하고 어떨때 인터페이스를 사용할까요?

그 외 템플릿 메서드 패턴, 추상화, 다형성, 상속의 개념을 정리하고
객체지향의 사실과 오해에서 나왔던 상속의 2가지 분류 서브클래싱 서브타이핑이라는 용어도 함께 정리해보는 것도 좋을 것 같습니다.

**Comment by YHLEE9753** [comment]
1장에서 연속적이라는 느낌이 드네요!! 추가적인 질문사항은 없습니다!

**Comment by ynoolee** [comment]
Discount 정책에서 저희 두 번째 과제였던 Voucher 가 생각이 났습니다
그 때도 이것을 추상클래스로 하느냐 인터페이스로 하느냐 고민이 많았었는데 
저는 처음에는 인터페이스로 작성 하였다가 후에는 추상클래스로 했었습니다.

그래서 저자는 어떤 기준에서 추상클래스와 인터페이스를 사용했을까에 대해 , 그리고 다른 분들은 추상 클래스와 인터페이스 중 어떤 것을 사용 하실지에 대해 한 번 얘기 해 보면 좋을 것 같습니다
